name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Bins:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2.2.2
    - shell: cmd
      run: |
        pushd ${{ github.workspace }}
        cd ../
        git clone https://github.com/Lord-Giganticus/Syati.git
        popd
    - name: Setup files
      shell: cmd
      run: |
        pushd ${{ github.workspace }}
        mkdir output
        cp -R source/. ../Syati/source
        cp -R include/. ../Syati/include
        cd ../Syati
        mkdir output
        popd
    - shell: pwsh
      run: |
        cd ${{ github.workspace }}/../Syati
        Invoke-WebRequest -Uri "https://cdn.discordapp.com/attachments/643925511906656257/829420068310876180/Kamek.rar" -OutFile Kamek.rar
        ${{ secrets.CODEWARRIOR_CMD }}
    - shell: cmd
      run: |
        cd ${{ github.workspace }}/../Syati
        7z x *.rar
        rm -f *.rar
        cd source
        rm -f ExtendedActorFactory.cpp
    - name: Build Syati
      shell: cmd
      run: |
         pushd ${{ github.workspace }}
         cd ../Syati
         Build USA PT
         Build PAL PT
         Build JAP PT
         Build KOR PT
         Build TWN PT
         mv *.bin output
         cp -R output/*.bin ../SMG2-Project-Template/output
         popd
    - run: |
        cd ${{ github.workspace }}
        cd ../Syati
        make
    - name: Upload bin files
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Bins
        path: ${{ github.workspace }}/output

  Loaders:
  
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - run: mkdir output
      shell: cmd
    - name: Clone Syati
      shell: cmd
      run: |
        pushd ${{ github.workspace }}
        cd ../
        git clone https://github.com/Lord-Giganticus/Syati.git
    - shell: pwsh
      run: |
        cd ${{ github.workspace }}/../Syati
        Invoke-WebRequest -Uri "https://cdn.discordapp.com/attachments/643925511906656257/829420068310876180/Kamek.rar" -OutFile Kamek.rar
        ${{ secrets.CODEWARRIOR_CMD }}
    - shell: cmd
      run: |
        cd ${{ github.workspace }}/../Syati
        7z x *.rar
        rm -f *.rar
        mkdir dols
    - shell: pwsh
      run: |
        cd ${{ github.workspace }}/../Syati
        cd dols
        ${{ secrets.USA_CMD }}
        ${{ secrets.PAL_CMD }}
        ${{ secrets.JAP_CMD }}
    - shell: cmd
      run: |
        cd ${{ github.workspace }}/../Syati
        cd loader
        bash -c ./build_USA.sh
        rm -f *.o
        bash -c ./build_PAL.sh
        rm -f *.o
        bash -c ./build_JAP.sh
        cd ../
        cp -R loader/out/*.xml ../SMG2-Project-Template/output
        cp -R loader/out/*.dol ../SMG2-Project-Template/output
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Loaders
        path: ${{ github.workspace }}/output
        
  Publish:
    if: github.ref == 'refs/heads/master'
    needs: [Bins, Loaders]
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2.3.4
      - run: |
          mkdir Release
          cd Release
          mkdir CustomCode
          mkdir Loaders
      - uses: actions/download-artifact@v2.0.10
        with: 
          name: Bins
          path: ${{ github.workspace }}/Release/CustomCode
      - uses: actions/download-artifact@v2.0.10
        with:
          name: Loaders
          path: ${{ github.workspace }}/Release/Loaders
      - shell: cmd
        run: |
          cd ${{ github.workspace }}/Release/Loaders
          rm -f *.xml
          cd ../
          7z a "${{ github.workspace }}/Syati.zip" *.* -r
          cd ${{ github.workspace }}
          7z a "${{ github.workspace }}/Syati.zip" SystemData objectdb.xml
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "Auto"
          prerelease: true
          title: "Auto Build"
          files: |
            *.zip
