name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Bins:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2.2.2
    - shell: cmd
      run: |
        pushd ${{ github.workspace }}
        cd ../
        git clone https://github.com/Lord-Giganticus/Syati.git
        popd
    - name: Curl Cache
      id: curl
      uses: actions/cache@v2.1.6
      with:
        path: C:\ProgramData\chocolatey\bin\curl.exe
        key: ${{ runner.os }}-curl
    - name: Install curl
      if: steps.curl.outputs.cache-hit != 'true'
      run: choco install curl --acceptlicense --confirm --verbose
      shell: cmd
    - name: Setup files
      shell: cmd
      run: |
        pushd ${{ github.workspace }}
        mkdir output
        cp -R source/. ../Syati/source
        cp -R include/spack/. ../Syati/include/spack
        cd ../Syati
        mkdir output
        curl -k -L https://cdn.discordapp.com/attachments/643925511906656257/829420068310876180/Kamek.rar -o Kamek.rar
        ${{ secrets.CODEWARRIOR_CMD }}
        7z x *.rar
        rm -f *.rar
        cd source
        rm -f ExtendedActorFactory.cpp
        popd
    - name: Build Syati
      shell: cmd
      run: |
         pushd ${{ github.workspace }}
         cd ../Syati
         python -m build USA
         rm -f *.d
         python -m build PAL
         rm -f *.d
         python -m build JAP
         rm -f *.d
         python -m build KOR
         rm -f *.d
         python -m build TWN
         rm -f *.d
         mv *.bin output
         cp -R output/*.bin ../SMG2-Project-Template/output
         popd
    - name: Upload bin files
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Bins
        path: ${{ github.workspace }}/output

  Loaders:
  
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Curl Cache
      id: curl
      uses: actions/cache@v2.1.6
      with:
        path: C:\ProgramData\chocolatey\bin\curl.exe
        key: ${{ runner.os }}-curl
    - name: Install curl
      if: steps.curl.outputs.cache-hit != 'true'
      run: choco install curl --acceptlicense --confirm --verbose
      shell: cmd
    - run: mkdir output
      shell: cmd
    - name: Clone Syati
      shell: cmd
      run: |
        pushd ${{ github.workspace }}
        cd ../
        git clone https://github.com/Lord-Giganticus/Syati.git
        cd Syati
        curl -k -L https://cdn.discordapp.com/attachments/643925511906656257/829420068310876180/Kamek.rar -o Kamek.rar
        ${{ secrets.CODEWARRIOR_CMD }}
        7z x *.rar
        rm -f *.rar
        mkdir dols
        cd dols
        ${{ secrets.USA_CMD }}
        ${{ secrets.PAL_CMD }}
        ${{ secrets.JAP_CMD }}
        cd ../loader
        bash -c ./build_USA.sh
        rm -f *.o
        bash -c ./build_PAL.sh
        rm -f *.o
        bash -c ./build_JAP.sh
        cd ../
        cp -R loader/out/*.xml ../SMG2-Project-Template/output
        cp -R loader/out/*.dol ../SMG2-Project-Template/output
        popd
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Loaders
        path: ${{ github.workspace }}/output
